# Generated by Django 4.1.5 on 2023-01-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=200)),
                ('comprehensiveness', models.CharField(max_length=200)),
                ('price_rate', models.CharField(max_length=200)),
                ('order_delivery', models.CharField(max_length=200)),
                ('customer_support', models.CharField(max_length=200)),
                ('recommend', models.CharField(max_length=200)),
            ],
        ),
    ]
