# Generated by Django 4.1.5 on 2023-01-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='expectations',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
